name: Rocq

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPAMROOT: /home/rocq/.opam
      SAIL_VERSION: "0.20"
    container:
      image: rocq/rocq-prover:9.0.1
      # github requires root to access some resources from outside the container
      # (e.g. https://github.com/actions/checkout/issues/47)
      options: --user root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          # Git history is needed for `git describe` in the build to work.
          fetch-depth: 0

      # The container doesn't appear to have full package information, unlike
      # the Ubuntu setup used in other workflows
      - name: Update Debian package information
        run: apt update

      - name: Common setup
        uses: ./.github/actions/sail-setup

      - name: Install Rocq-specific opam packages
        run: |
          eval `opam env --safe`
          opam update
          # We're still using Rocq's old name for compatibility with versions < 9
          opam install -y coq=9.0.1 coq-sail-stdpp=$SAIL_VERSION

      - name: Generate Rocq model
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DDOWNLOAD_GMP=FALSE
          cmake --build build --target generated_rocq_rv64d

      - name: Compile Rocq output
        run: |
          eval `opam env --safe`
          cmake --build build --target build_rocq_rv64d
