name: Rocq

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPAMROOT: /home/rocq/.opam
      SAIL_VERSION: "0.19.1"
    container:
      image: rocq/rocq-prover:9.0.0
      # github requires root to access some resources from outside the container
      # (e.g. https://github.com/actions/checkout/issues/47)
      options: --user root
    steps:
      - name: Install packages
        run: |
          apt update
          apt install -y --no-install-recommends cmake cargo
          eval `opam env --safe`
          # We're still using Rocq's old name for compatibility with versions < 9
          opam install -y coq=9.0.0 coq-sail-stdpp=$SAIL_VERSION

      - name: Install sail from binary
        run: |
          curl --location https://github.com/rems-project/sail/releases/download/$SAIL_VERSION-linux-binary/sail.tar.gz | tar xvz --directory=/usr/local --strip-components=1

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Generate Rocq model
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DDOWNLOAD_GMP=FALSE
          cmake --build build --target generated_rocq_rv64d

      - name: Compile Rocq output
        run: |
          eval `opam env --safe`
          cmake --build build --target build_rocq_rv64d
