name: Build and test Lean backend

on: [push, pull_request, workflow_dispatch]

env:
  OPAMVERBOSE: 1
  CLEAR_GLOBS_FILE: .github/workflows/clear-globs.txt

jobs:
  build:
    strategy:
      matrix:
        version: [5.2.1]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Checkout SAIL
      run: |
        git clone https://github.com/rems-project/sail.git

    - name: System dependencies (ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt install build-essential libgmp-dev z3 cvc4 opam

    - name: Restore cached opam
      id: cache-opam-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.opam
        key: ${{ matrix.os }}-${{ matrix.version }}

    - name: Setup opam
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      run: |
        opam init --yes --no-setup --shell=sh --compiler=${{ matrix.version }}
        opam install dune

    - name: Save cached opam
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      id: cache-opam-save
      uses: actions/cache/save@v4
      with:
        path: ~/.opam
        key: ${{ steps.cache-opam-restore.outputs.cache-primary-key }}

    - name: Install Sail
      run: |
        eval $(opam env)
        (cd sail; opam install sail --deps-only --yes)
        (cd sail; make install)

    - name: Build the Sail RISCV Model for Lean
      run: |
        git clone https://github.com/riscv/sail-riscv.git
        cd sail-riscv
        eval $(opam config env)
        cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
        # This patch is needed to work around https://github.com/rems-project/sail/issues/1003.
        patch -p1 < ../.github/workflows/build-riscv-lean-workaround-riscv.patch
        cmake --build build/ --target generated_lean_rv64d
        cd ..

    - name: Use Lean to build the model and report errors
      run: |
        wget -q https://raw.githubusercontent.com/leanprover-community/mathlib4/master/scripts/install_debian.sh
        bash install_debian.sh ; rm -f install_debian.sh
        source ~/.profile
        cp README.md.template sail-riscv/build/model/Lean_RV64D_LEAN/
        cp report.py sail-riscv/build/model/Lean_RV64D_LEAN/
        cd sail-riscv/build/model/Lean_RV64D_LEAN/
        echo "Set ulimit"
        ulimit -s unlimited
        ulimit -s
        lake build
